[package]
name = "task-generator"
version = "0.1.0"
authors = ["kawadumax <kazmax7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gimei = "0.2"
printpdf = "0.3.2"